version: "3"
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    container_name: zookeeper
    hostname: ${HOSTNAME}
    ports:
      - 2181:2181
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - 9092:9092
    container_name: kafka
    hostname: ${HOSTNAME}
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  aerospike:
    image: 'aerospike'
    container_name: aerospike
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    volumes:
      - 'aerospike_data:/opt/aerospike/data'
      
volumes:
  kafka_data:
  zookeeper_data:
  aerospike_data:
